# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    versioning-strategy: "increase-minor"
  - package-ecosystem: "pip"
    directory: "backend/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "flask"
        versions: ["1.0.0", "1.1.0"]
    pull-request-branch-name:
      prefix: "dependabot-pip-update"
